name: Ejecutar trifásica

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-trifasica:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ejecutar cálculo trifásico
        run: python estrellaDesbalanceada.py